name: SirsiNexus
title: SirsiNexus - Cloud Infrastructure Management
description: SirsiNexus revolutionizes cloud infrastructure management through Graph of Thought AI architecture and Hedera Hashgraph technology.

# Build settings
permalink: pretty
exclude: [
  "README.md",
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "package.json",
  "package-lock.json"
]

# Jekyll settings
include: [".htaccess"]
keep_files: [".git"]

# Default front matter
defaults:
  -
    scope:
      path: "" # Apply to all files
    values:
      layout: "default"
