name: SirsiNexus
title: SirsiNexus - Cloud Infrastructure Management
description: SirsiNexus revolutionizes cloud infrastructure management through Graph of Thought AI architecture and Hedera Hashgraph technology.

# Build settings
permalink: pretty
baseurl: "/SirsiNexusPortal"
url: "https://sirsimaster.github.io"

# Directory structure
source: .
destination: ./_site

# File handling
exclude: [
  "README.md",
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "package.json",
  "package-lock.json"
]
include: [
  ".htaccess",
  "_redirects"
]
keep_files: [
  ".git",
  "CNAME"
]

# Default front matter
defaults:
  -
    scope:
      path: "" # Apply to all files
    values:
      layout: "default"

# URL handling
force_https: true
