name: GitHub Pages deployment

on:
  push:
    branches: 
      - main            # Production deployment
      - 'staging/**'    # Any staging branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Create deployment structure
        run: |
          echo "Creating deployment structure with SirsiNexusPortal directory"
          mkdir -p _site
          cp -r SirsiNexusPortal _site/
          echo "Verifying structure:"
          ls -la _site/
          ls -la _site/sirsinexusportal/index*.html
      
      - name: Copy index to staging for non-main branches
        if: github.ref != 'refs/heads/main'
        run: |
          cp _site/sirsinexusportal/index.html _site/sirsinexusportal/index-staging.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
